
# no id makes all papers to appear the same as this one, so I give the fake ID
- id: doi:10.5555/12345678
  title: "Noun-MWP: Math Word Problems Meet Noun Answers"
  authors:
    - Taehun Cha
    - Jaeheun Jung
    - Donghun Lee
  publisher: "Proceedings of the 29th International Conference on Computational Linguistics"
  date: "2022-10-17"
  link: "https://aclanthology.org/2022.coling-1.338/"
