- title: "Noun-MWP: Math Word Problems Meet Noun Answers"
  authors:
    - Taehun Cha
    - Jaeheun Jung
    - Donghun Lee
  publisher: ACL Anthology
  date: '2022-10-17'
  link: "https://aclanthology.org/2022.coling-1.338/"

- id: "doi:10.1007/978-3-031-05936-0_26"
  date: '2020-05-16'

